name: Submit code to the Kaggle competition

on:
  push:
  workflow_dispatch:
  
env:
  COMPETITION_NAME: cmp2003-rating-prediction
jobs:
  kaggle-submitter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Kaggle
        uses: osbm/kaggle-login@main
        with:
          KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
          KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}

      - name: Run the code
        run: |
          make && ./main
          
      - name: Upload the submission file
        uses: actions/upload-artifact@v2
        with:
          name: submission
          path: submission.csv

      - name: Submit to Kaggle
        run: |
          kaggle competitions submit -c ${{ env.COMPETITION_NAME }} -f submission.csv -m "Auto submit from GitHub Actions current branch: $GITHUB_REF commit hash: $GITHUB_SHA"

      - name: Get the last score from Kaggle
        run: |
          pip install pandas
          python .github/scripts/get_kaggle_score.py ${{ env.COMPETITION_NAME }}
          
      - name: Make a tag including the score
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git tag -a ${{ env.KAGGLE_SCORE }} -m "Auto tag from GitHub Actions current branch: $GITHUB_REF commit hash: $GITHUB_SHA"
          git push --tags
